- name: Copy scripts into /usr/local/bin
  become: true
  become_user: root
  ansible.builtin.copy:
    src: files/
    dest: /usr/local/bin
  tags:
    - scripts

- name: Give scripts execute permissions
  become: true
  become_user: root
  shell: |
    cd /usr/local/bin && 
    chmod +x ./backup &&
    chmod +x ./birthday &&
    chmod +x ./loggy &&
    chmod +x ./newscript
  tags:
    - scripts
