- name: Create symlinks for scripts
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename }}"
    state: link
    force: true
    mode: u=rwx,g=rwx,o=rwx
  with_fileglob:
    - "{{ role_path }}/files/*"
