- name: Copy scripts into /usr/local/bin
  become: true
  become_user: root
  ansible.builtin.copy:
    src: files/
    dest: /usr/local/bin
  tags:
    - scripts

- name: Give scripts execute permissions
  become: true
  become_user: root
  shell: |
    cd /usr/local/bin && 
    chmod +x ./backup.sh &&
    chmod +x ./birthday.sh &&
    chmod +x ./loggy.sh &&
    chmod +x ./newscript.sh
  tags:
    - scripts
