- hosts: localhost
  become: true
  pre_tasks:
  - name: System details
    include_tasks: pre_tasks/system_details.yml
  - name: Update cache
    include_tasks: pre_tasks/update_cache.yml
  - name: Check brew is on the system
    include_tasks: pre_tasks/check_brew.yml
  roles:
  # - './roles/system'
  # - './roles/zsh'
  - './roles/tmux'