- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache (I want all my repos be up to date)
    apt:
      update_cache: true
    tags: 
    - zsh
    # - node
    - system
    - stow
    - dotfiles
    - scripts
    - nvim
  roles:
  - './roles/system'
  - './roles/zsh'