- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache (I want all my repos be up to date)
    apt:
      update_cache: true
    tags: 
    - zsh
    - node
  tasks:
  - name: Include task zsh
    import_tasks: tasks/zsh.yml
  - name: Include task node
    import_tasks: tasks/node.yml
