- name: Clone Neovim
  become: true
  become_user: root
  ansible.builtin.git:
    depth: 1
    repo: 'https://github.com/neovim/neovim.git'
    dest: "~/neovim"
  tags:
    - nvim

- name: Build neovim
  become: true
  become_user: root
  shell: "cd ~/neovim && make -j 20"
  tags:
    - nvim

- name: Install neovim
  become: true
  become_user: root
  shell: "cd ~/neovim && make install"
  tags:
    - nvim

- name: Clone LazyVim into .dotfiles
  become: true
  become_user: root
  ansible.builtin.git:
    depth: 1
    repo: 'https://github.com/LazyVim/starter'
    dest: ".dotfiles/nvim/.config/nvim"
  tags:
    - nvim