#!/bin/bash

# Author: Friedrich
# Date Created: 5.2.24
# Date Modified: 5.2.24

# Description:
# Logs the provided message with a timestamp

# Usage:
# loggy "here comes your message"

echo `date +'%F %T'` $* >> `date +%F`.log

exit 0