# TODO: check "sudo rm -rf /opt/nvim", it is installed into "/opt/nvim-linux64" on mac
- name: Download and install Neovim
  shell: |
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    sudo rm -rf /opt/nvim
    sudo tar -C /opt -xzf nvim-linux64.tar.gz
  become: true
  become_user: fedjaw

- name: Create directory ~/.config/nvim if it does not exist
  ansible.builtin.file:
    path: "$HOME/.config/nvim"
    state: directory
    mode: "0755"
  become: true
  become_user: fedjaw

- name: Create symlink for nvim config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "$HOME/.config/nvim"
    state: link
    force: true
  become: true
  become_user: fedjaw
