# TODO: check "sudo rm -rf /opt/nvim", it is installed into "/opt/nvim-linux64" on mac 
- name: Download and install Neovim
  become: true
  become_user: root
  shell: |
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    sudo rm -rf /opt/nvim
    sudo tar -C /opt -xzf nvim-linux64.tar.gz

- name: Create directory ~/.config/nvim if it does not exist
  ansible.builtin.file:
    path: "$HOME/.config/nvim"
    state: directory
    mode: '0755'

- name: Create symlink for nvim config
  become: true
  become_user: root
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "$HOME/.config/nvim"
    state: link
    force: true
